spring.application.name=GuideMitra
spring.datasource.url=jdbc:postgresql://dpg-d23od1ndiees739rrh70-a:5432/guideuserdb?sslmode=require
spring.datasource.username=guideuserdb_user
spring.datasource.password=Q6VxMPKr4i2RXtp0PAErlO42UL5ILcKq
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=guidemitra
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=guide-mitra

