spring.application.name=GuideMitra
spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/guidemitra
spring.datasource.username=guidemitra
spring.datasource.password=iips@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
