services:
  - type: web
    name: guide-mitra-py
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi
