services:
  - type: web
    name: guide-mitra-py
    env: python
    rootDir: Backend/backend
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 10000
