FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=guidedetails
ENV MYSQL_USER=guidemitra
ENV MYSQL_PASSWORD=iips@123

# Expose port 3306 for MySQL
EXPOSE 3306
